# backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000  # Assuming the backend app listens on port 8080

